name: Development_merge

on:
  workflow_run:
    workflows: [Development]
    branches-ignore:
      - 'main'
      - 'dev'
      - 'staging'
    types:
      - completed
  workflow_dispatch:

jobs:
  quality-assurance:
    name: 'Development merge'
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Terraform init'
        id: init
        run: terraform init
        
      - name: 'Terraform plan'
        id: plan
        run: terraform plan

      - name: 'Terraform apply'
        id: apply
        run: terraform apply --auto-approve