name: Development

on:
  push:
    branches-ignore:
      - 'main'
      - 'dev'
      - 'staging'
  workflow_dispatch:

jobs:
  quality-assurance:
    name: 'Development'
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        
      - name: 'Terraform init'
        id: init
        run: terraform init

      - name: 'Terraform fmt'
        id: fmt
        run: terraform fmt

      - name: 'Terraform validate'
        id: validate
        run: terraform validate

      - name: 'Tflint'
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.44.1

      - name: Show version
        run: tflint --version
    
      - name: Init TFLint
        run: tflint --init
        env:
          # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
          GITHUB_TOKEN: ${{ github.token }}
    
      - name: Run TFLint
        run: tflint -f compact

  merge-branch:
    name: 'Dev merge'
    needs: quality-assurance
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  
    permissions:
      contents: write

    steps:
      - name: Merge with dev
        uses: devmasx/merge-branch@master

        with:
          type: now
          from_branch: ${{ GITHUB.ref_name }}
          target_branch: dev
          github_token: ${{ secrets.GITHUB_TOKEN }}
