name: Development

on:
  push:
    branches-ignore:
      - 'main'
    paths:
      - 'iac_assignment_2/**'
  workflow_dispatch:

jobs:
  terraform:
    name: 'Development'
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      WORKING_DIR: ./iac_assignment_2
      
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        
      - name: 'Terraform init'
        id: init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}
